apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://localhost:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60
