#!/usr/bin/env python3
"""Render docs/FAQ.md into the website's faq.html: tools/gen-faq-html.py [--check] [--out PATH]

What it does, in order:
  1. reads docs/FAQ.md and parses it as the small markdown subset that file
     uses -- `##` sections, `###` questions, paragraphs, bullet lists, pipe
     tables and fenced code blocks;
  2. renders each question as one of the site's `.teach-card` blocks and each
     section as the site's uppercase rule heading;
  3. splices the result into the target page between the FAQ:BEGIN and FAQ:END
     markers, leaving every other byte of the page -- head, topbar, sidebar,
     footer, scripts -- exactly as it was.

Why this exists rather than an edited HTML file: the site's FAQ shipped for
months claiming a seven-distribution menu that no longer existed, because the
answers lived only in the page. The markdown is now the source of truth and the
page is a build artifact, so the two cannot disagree. `--check` is the CI form
and changes nothing.

Everything in docs/FAQ.md before its first `## ` heading is repo-internal and is
NOT rendered, with one exception: the `**Last checked against the tree:**` line
becomes the page's freshness note, because a FAQ's readers deserve to know how
old the answers are.

Inputs:  docs/FAQ.md, and the target page (default ../kldload-web/faq.html,
         relative to the repo root; override with --out).
Outputs: the target page, rewritten in place.

Exit: 0 written (or, with --check, already current), 1 out of date or the
markers are missing, 2 usage.

Notes:
  - The subset is deliberate. Anything markdown can do that is not listed above
    will be emitted as literal text, which is loud and easy to spot, rather
    than silently dropped.
  - The generated block is asserted after writing: the card count in the file
    has to match the question count in the markdown, or this exits 1. An edit
    that silently applies to nothing is worse than one that errors.
"""

import argparse
import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN = "<!-- FAQ:BEGIN  generated by tools/gen-faq-html.py from docs/FAQ.md -- do not edit -->"
END = "<!-- FAQ:END -->"

SECTION_STYLE = (
    'style="color:var(--accent);font-size:0.95rem;text-transform:uppercase;'
    'letter-spacing:0.06em;border-bottom:1px solid var(--border);'
    'padding-bottom:0.4rem;margin-top:2rem"'
)


def slug(text: str) -> str:
    """A stable anchor id: lower case, words joined by hyphens."""
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def inline(text: str) -> str:
    """Markdown inline spans -> HTML.

    Code spans are lifted out to placeholders FIRST and put back LAST, so their
    contents are never touched -- a `--flag` in backticks must not become an em
    dash. They are placeholders rather than finished HTML because bold wraps
    code often enough to matter: splitting on backticks and running the bold
    regex per fragment left `**`apt`, `dnf` ...**` with its literal asterisks on
    the page (caught in the first render, 2026-09-20).
    """
    spans: list[str] = []

    def stash(m: "re.Match[str]") -> str:
        spans.append(html.escape(m.group(1)))
        return f"\x00{len(spans) - 1}\x00"

    s = re.sub(r"`([^`]+)`", stash, text)
    s = html.escape(s)
    s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<!-)--(?!-)", "&mdash;", s)
    return re.sub(r"\x00(\d+)\x00", lambda m: f"<code>{spans[int(m.group(1))]}</code>", s)


def render_table(rows: list[str]) -> str:
    """A pipe table -> <table>. Row 1 is the header, row 2 the separator."""
    cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in rows]
    head, body = cells[0], cells[2:]
    out = ["<table>", "<thead><tr>"]
    out += [f"<th>{inline(c)}</th>" for c in head]
    out.append("</tr></thead><tbody>")
    for row in body:
        out.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in row) + "</tr>")
    out.append("</tbody></table>")
    return "".join(out)


def render_body(lines: list[str], first_margin: bool = False) -> list[str]:
    """One answer's lines -> its HTML blocks, in order."""
    out: list[str] = []
    i, n = 0, len(lines)
    while i < n:
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        margin = ' style="margin-top:0.6rem"' if out or first_margin else ""
        if line.startswith("```"):
            code = []
            i += 1
            while i < n and not lines[i].startswith("```"):
                code.append(lines[i])
                i += 1
            i += 1
            out.append(f"<pre><code>{html.escape(chr(10).join(code))}</code></pre>")
        elif line.lstrip().startswith("|"):
            rows = []
            while i < n and lines[i].lstrip().startswith("|"):
                rows.append(lines[i])
                i += 1
            out.append(render_table(rows))
        elif line.lstrip().startswith("- "):
            items = []
            while i < n and lines[i].lstrip().startswith("- "):
                item = [lines[i].lstrip()[2:]]
                i += 1
                while i < n and lines[i].startswith("  ") \
                        and not lines[i].lstrip().startswith("- "):
                    item.append(lines[i].strip())
                    i += 1
                items.append(" ".join(item))
            out.append("<ul>" + "".join(f"<li>{inline(t)}</li>" for t in items) + "</ul>")
        else:
            para = []
            while i < n and lines[i].strip() and not lines[i].startswith(("```", "|", "- ")):
                para.append(lines[i].strip())
                i += 1
            out.append(f"<p{margin}>{inline(' '.join(para))}</p>")
    return out


def render(md: str) -> tuple[str, int]:
    """The markdown -> the page's inner HTML, and the number of questions."""
    lines = md.splitlines()
    checked = ""
    for line in lines:
        if line.startswith("**Last checked against the tree:**"):
            checked = inline(
                line.replace("**Last checked against the tree:**", "").strip().rstrip("."))
            break

    out = [
        "<section>",
        '<div class="section-label">Learn</div>',
        '<h2 style="border:none" id="frequently-asked-questions">Frequently Asked Questions</h2>',
        '<p class="prose">What kldload is, what it does to your machine, and what it '
        "does not do. Every answer is checked against the source tree rather than "
        f"remembered{('; last checked ' + checked) if checked else ''}.</p>",
    ]
    questions = 0
    i, n = 0, len(lines)
    while i < n and not lines[i].startswith("## "):
        i += 1
    while i < n:
        line = lines[i]
        if line.startswith("## "):
            title = line[3:].strip()
            out.append(f'<h3 {SECTION_STYLE} id="{slug(title)}">{inline(title)}</h3>')
            i += 1
        elif line.startswith("### "):
            title = line[4:].strip()
            body: list[str] = []
            i += 1
            while i < n and not lines[i].startswith(("## ", "### ")):
                body.append(lines[i])
                i += 1
            while body and not body[-1].strip():
                body.pop()
            if body and body[-1].strip() == "---":
                body.pop()
            questions += 1
            out.append('<div class="teach-card" style="margin-bottom:1rem">')
            out.append(f'<h4 id="{slug(title)}">{inline(title)}</h4>')
            out += render_body(body)
            out.append("</div>")
        else:
            i += 1
    out.append("</section>")
    return "\n      ".join(out), questions


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    ap.add_argument("--out", default=str(ROOT.parent / "kldload-web" / "faq.html"),
                    help="the page to splice into (default: ../kldload-web/faq.html)")
    ap.add_argument("--check", action="store_true",
                    help="report whether the page is current; write nothing")
    a = ap.parse_args()

    src = ROOT / "docs" / "FAQ.md"
    if not src.is_file():
        print(f"gen-faq-html: no {src}", file=sys.stderr)
        return 1
    page = pathlib.Path(a.out)
    if not page.is_file():
        print(f"gen-faq-html: no page at {page}", file=sys.stderr)
        return 1

    body, questions = render(src.read_text(encoding="utf-8"))
    text = page.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"gen-faq-html: {page} has no FAQ:BEGIN/FAQ:END markers -- add them "
              "around the content block first", file=sys.stderr)
        return 1

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{BEGIN}\n      {body}\n      {END}{tail}"
    if a.check:
        if new == text:
            print(f"gen-faq-html: {page} is current ({questions} questions)")
            return 0
        print(f"gen-faq-html: {page} is OUT OF DATE -- run tools/gen-faq-html.py",
              file=sys.stderr)
        return 1

    page.write_text(new, encoding="utf-8")
    # Assert the edit landed: the page has to carry one card per question.
    cards = page.read_text(encoding="utf-8").count('<div class="teach-card"')
    if cards != questions:
        print(f"gen-faq-html: wrote {page} but it has {cards} cards for "
              f"{questions} questions", file=sys.stderr)
        return 1
    print(f"gen-faq-html: {page}: {questions} questions in "
          f"{body.count('<h3 ')} sections")
    return 0


if __name__ == "__main__":
    sys.exit(main())
